name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Lancer sur chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build project
        run: |
          cd dynamodb-visualization/
          npm install
          npm run build  # ou d'autres commandes de build selon ton projet

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # ou le répertoire à déployer (si ton build produit des fichiers dans un sous-dossier)

